name: ' Publish To AppSource'
run-name: 'Publish To AppSource - Version ${{ inputs.appVersion }}, Projects ${{ inputs.projects }}'

on:
  workflow_dispatch:
    inputs:
      appVersion:
        description: App version to deliver to AppSource (current, prerelease, draft, latest or version number)
        required: false
        default: 'current'
      projects:
        description: Projects to publish to AppSource if the repository is multi-project. Default is *, which will publish all projects to AppSource.
        required: false
        default: '*'
      GoLive:
        description: Promote AppSource App to go live if it passes technical validation?
        type: boolean
        default: false

permissions:
  actions: read
  contents: read
  id-token: write

defaults:
  run:
    shell: pwsh

env:
  ALGoOrgSettings: ${{ vars.ALGoOrgSettings }}
  ALGoRepoSettings: ${{ vars.ALGoRepoSettings }}

jobs:
  Initialization:
    needs: [ ]
    runs-on: [ ubuntu-latest ]
    outputs:
      telemetryScopeJson: ${{ steps.init.outputs.telemetryScopeJson }}
    steps:
      - name: Dump Workflow Information
        uses: aholstrup1/AL-Go/Actions/DumpWorkflowInfo@aholstrup/codeanalysis_defensivecheck
        with:
          shell: pwsh

      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Initialize the workflow
        id: init
        uses: aholstrup1/AL-Go/Actions/WorkflowInitialize@aholstrup/codeanalysis_defensivecheck
        with:
          shell: pwsh

  Deliver:
    needs: [ Initialization ]
    runs-on: [ ubuntu-latest ]
    name: Deliver to AppSource
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Read settings
        uses: aholstrup1/AL-Go/Actions/ReadSettings@aholstrup/codeanalysis_defensivecheck
        with:
          shell: pwsh

      - name: Read secrets
        id: ReadSecrets
        uses: aholstrup1/AL-Go/Actions/ReadSecrets@aholstrup/codeanalysis_defensivecheck
        with:
          shell: pwsh
          gitHubSecrets: ${{ toJson(secrets) }}
          getSecrets: 'appSourceContext'

      - name: Deliver
        uses: aholstrup1/AL-Go/Actions/Deliver@aholstrup/codeanalysis_defensivecheck
        env:
          Secrets: '${{ steps.ReadSecrets.outputs.Secrets }}'
        with:
          shell: pwsh
          type: 'Release'
          projects: ${{ github.event.inputs.projects }}
          deliveryTarget: 'AppSource'
          artifacts: ${{ github.event.inputs.appVersion }}
          goLive: ${{ github.event.inputs.goLive }}

  PostProcess:
    needs: [ Initialization, Deliver ]
    if: always()
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Finalize the workflow
        id: PostProcess
        uses: aholstrup1/AL-Go/Actions/WorkflowPostProcess@aholstrup/codeanalysis_defensivecheck
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          shell: pwsh
          telemetryScopeJson: ${{ needs.Initialization.outputs.telemetryScopeJson }}
          currentJobContext: ${{ toJson(job) }}
